# Generated by Django 4.2.16 on 2024-11-09 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="название")),
                ("password", models.CharField(max_length=150, verbose_name="название")),
            ],
            options={
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
            },
        ),
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="название")),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="опубликовано"),
                ),
                (
                    "is_anonymous",
                    models.BooleanField(default=False, verbose_name="анонимно"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="слаг"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="catalog_users",
                        to="catalog.user",
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "опрос",
                "verbose_name_plural": "опросы",
            },
        ),
        migrations.CreateModel(
            name="OnlyResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=150, verbose_name="вопрос")),
                (
                    "is_free",
                    models.BooleanField(default=False, verbose_name="есть ответ"),
                ),
                ("answer", models.TextField(verbose_name="верый ответ")),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.survey",
                        verbose_name="опрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "одиночный вопросы",
                "verbose_name_plural": "одиночные вопросы",
            },
        ),
        migrations.CreateModel(
            name="MultipleResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=150, verbose_name="вопрос")),
                (
                    "is_free",
                    models.BooleanField(default=False, verbose_name="есть ответ"),
                ),
                ("answer", models.TextField(verbose_name="верый ответ")),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.survey",
                        verbose_name="опрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "многовариантные вопросы",
                "verbose_name_plural": "многовариантные вопросы",
            },
        ),
        migrations.CreateModel(
            name="AnswerOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_right",
                    models.BooleanField(default=False, verbose_name="правильный"),
                ),
                ("answer", models.TextField(verbose_name="верый ответ")),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="catalog_responses",
                        to="catalog.multipleresponse",
                        verbose_name="опрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "вариант ответа",
                "verbose_name_plural": "варианты ответа",
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="имя")),
                ("text", models.TextField(verbose_name="ответ")),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.survey",
                        verbose_name="опрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "ответ",
                "verbose_name_plural": "ответы",
            },
        ),
    ]
