# Generated by Django 4.2.16 on 2024-11-09 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="имя"
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="survey",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.survey",
                verbose_name="опрос",
            ),
        ),
        migrations.AlterField(
            model_name="multipleresponse",
            name="survey",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.survey",
                verbose_name="опрос",
            ),
        ),
        migrations.AlterField(
            model_name="onlyresponse",
            name="survey",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.survey",
                verbose_name="опрос",
            ),
        ),
    ]
